server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oh?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  main:
    allow-circular-references: true

# 配置mybatis实体和xml映射
mybatis:
  #resources???????src?????????mapper????
  mapper-locations: classpath*:mappers/*.xml
  #?????
  type-aliases-package: com.example.entity
  #????????????????SQL???
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql